- package-lock.json
- package.json
- server.js
- tsconfig.json
> feat: 초기세팅

- package.json
package.json에 npm start 관련 내용 추가
- https://mysterysketch.atlassian.net/browse/BACK-6?atlOrigin=eyJpIjoiMDJjMWJiY2Q1MGYwNGY5NDg3ZWZmY2ZmYTMwOGQ3YjQiLCJwIjoiaiJ9
> feat: 초기세팅 수정

- src/controllers/userController.js
- src/models/userDao.js
- src/routes/userRouter.js
- src/services/userService.js
- src/utils/error.js
feat: post 유저등록 API 구현했습니다
유저가입 및 게임방 입장 시 게임 방 정원수와 현재 참여자수를 비교하여 참여가 가능하면 참가하게 하고,
참여가 불가능하면 새로운 방을 만들어 입장하게 하였습니다.
> feat: post 유저등록 API 구현

- .gitignore
- app.js
- src/controllers/imageController.js
- src/models/dataSource.js
- src/models/imageDao.js
- src/routes/imageRouter.js
- src/routes/index.js
- src/services/imageService.js
Feat: 유저 Profile Image GET API 기능 구현 및 .env gitignore 수정했습니다.
> Feat: 유저 Profile Image Get API 기능 구현, .env gitignore 수정

- app.js
- package-lock.json
- package.json
app.js에 socket 기본 통신구현하는 코드와 npm socket io 설치
> feat: socket 기본 통신구현

- app.js
> fix: socket io 통신 수정

- src/models/userDao.js
- src/services/userService.js
일반유저 공개방만 접근하도록 코드 수정!
is_private = 0 인 방만 찾도록 구성하였습니다.
> Fix: 일반유저 공개방만 접근하도록 코드 수정

- src/controllers/gameRoomController.js
- src/models/gameRoomDao.js
- src/routes/gameRoomRouter.js
- src/routes/index.js
- src/services/gameRoomService.js
Feat: 게임 방 정보 및 참여유저 정보 전달 API 구현했습니다!
> Feat: 게임 방 정보 및 참여유저 정보 전달 API 구현

- src/models/gameRoomDao.js
https://www.notion.so/Backend-API-270000d9611a4053b7471d4701096ec6
접속경로: GET 43.203.93.116:8000/api/gameRoom/:roomId
> feat : 게임방 image_Link 추가

- src/controllers/userController.js
- src/models/userDao.js
- src/routes/userRouter.js
- src/services/userService.js
> Feat: 비밀방 생성 API 구현

- src/controllers/userController.js
- src/models/userDao.js
- src/services/userService.js
Fix: 비밀방 생성 API request body 값 수정
방 설정 값도 받아와서 해당 값으로 방 만들게 수정
> Fix: 비밀방 생성 API request body 값 수정

- src/controllers/socketController.js
> feat: 실시간 그림 기능 구현

- src/controllers/socketController.js
> feat: 실시간 유저 업데이트  기능 구현

- src/controllers/socketController.js
> fix: socketController gameRoomDao 연동 수정

- src/controllers/socketController.js
> fix: socketController draw socket.emit 파라미터  수정

- src/controllers/socketController.js
> feat: 실시간 컬러변경 기능

- src/controllers/socketController.js
- src/models/gameRoomDao.js
> feat: 실시간 타이머 기능 구현

- src/controllers/socketController.js
> feat: 실시간 그림 지우개 기능구현

- src/controllers/socketController.js
> feat: socket game start 기능구현

- src/controllers/gameRoomController.js
- src/models/gameRoomDao.js
- src/routes/gameRoomRouter.js
- src/services/gameRoomService.js
> feat: put 현재 진행 라운드 update  기능

- src/controllers/socketController.js
- src/models/gameRoomDao.js
> feat: socket 현재 진행 라운드 기능 구현

- src/controllers/userController.js
- src/models/userDao.js
- src/services/userService.js
> fix : 유저 닉네임 중복불가로 수정

- src/controllers/socketController.js
> feat : "실시간 그림 그리기 권한 socket"

- src/controllers/answerController.js
- src/models/answerDao.js
- src/routes/answerRouter.js
- src/services/answerService.js
> feat 랜덤단어 수정

- src/controllers/socketController.js
- src/models/userDao.js
socket 연결 끊길 시 일시적 유저 삭제 및 유저목록 업데이트
> fix: socket disconnected 유저 삭제 & 유저목록 업데이트

- src/controllers/gameRoomController.js
- src/models/gameRoomDao.js
- src/routes/gameRoomRouter.js
- src/services/answerService.js
- src/services/gameRoomService.js
연필권한을  라운드마다 첫번째 유저부터 차례대로 주는 API
> 연필 권한 주기 기능 추가

- src/controllers/gameRoomController.js
- src/models/gameRoomDao.js
- src/routes/gameRoomRouter.js
- src/services/gameRoomService.js
> 연필권한 주기 (삭제)

- src/controllers/socketController.js
> 실시간 추방 기능(방장 권한) 구현

- src/controllers/socketController.js
> 실시간 문제 공유 기능 구현

- src/controllers/socketController.js
- src/models/userDao.js
> 실시간 유저 포인트 추가 기능 구현

- src/controllers/gameRoomController.js
- src/models/gameRoomDao.js
- src/routes/gameRoomRouter.js
- src/services/gameRoomService.js
라운드마다 방에 입장한 유저  첫번째부터 그림그리기 권한 주기
> 라운드마다 그림그리기 권한주는 기능

- src/controllers/socketController.js
- src/models/gameRoomDao.js
- src/models/userDao.js
그리기 권한 함수 방장권한 등등 여러 함수 수정 및 구현
> 그리기권한 관련 함수 & socket , 방장권한 관련 함수 & socket
